controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /index
    controller: App\Controller\PageRenderController::index
   
user_index:
    path: /users
    controller: App\Controller\UserController::index

