controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /index
    controller: App\Controller\PageRenderController::index
   
registration:
    path: /registration
    controller: App\Controller\RegistrationController::index

user_index:
    path: /users
    controller: App\Controller\UserController::index

